[workspace]
resolver = "2"
members = ["xtask", "crates/*"]
default-members = ["crates/app"]

[workspace.package]
authors = ['enpitsulin <enpitsulin@gmail.com>']
license = "MIT"
repository = "https://github.com/enpitsulin/aria2-gpui"
description = "A personal gpui boilerplate"
rust-version = "1.89"
publish = false
edition = "2024"

[workspace.dependencies]

#
# Workspace member crates
#
ui = { path = "crates/ui" }

#
# External crates
#
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0.86"
cargo_metadata = "0.23"
cargo_toml = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }

# GPUI
gpui = "0.2.0"
gpui-component = "0.5.0"


[workspace.dependencies.windows]
version = "0.62"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Credentials",
    "Win32_System_Threading"
]
