max_width = 110
newline_style = "Unix"
trailing_comma = "Never"
match_block_trailing_comma = true
tab_spaces = 4
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
indent_style = "Block"
normalize_comments = false
imports_granularity = "Module"
group_imports = "StdExternalCrate"
