[toolchain]
channel = "nightly-2025-09-12"
profile = "minimal"
components = ["rustfmt", "clippy"]
targets = [
	"x86_64-apple-darwin",
	"aarch64-apple-darwin",
	"x86_64-unknown-linux-gnu",
	"x86_64-pc-windows-msvc",
]
